baseURL = 'https://example.infotecha.ru/'
languageCode = 'ru-ru'
title = 'Базовый модуль образовательной платформы'
theme = 'compose'

[params]
  # Секции для навигации по курсу
  docSections = ["intro", "theme_01", "theme_02", "theme_03", "theme_04", "outro"]
  
  # Настройки источника (GitHub)
  [params.source]
    name = "GitHub"
    iconLight = "images/GitHubMarkLight.svg"
    iconDark = "images/GitHubMarkDark.svg"
    url = "https://github.com/info-tech-io/"

  # Настройки платформы
  [params.platform]
    hub_url = "https://infotecha.ru"
    quiz_engine_path = "/quiz/src/quiz-engine/quiz-engine.mjs"

# Логотип
[logo]
  text = "InfoTech.io"

# Настройки разметки для поддержки shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    noClasses = false